#include "Logger.h"

#define PWM_MAX_WIDTH 1023

#define CON_DEBUG_LEVEL_ALL 1
#define LOG_LEVEL_DETAIL_DEBUG 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NOTHING 5

/**
 * Уровень логирования
 */
#define LOG_LEVEL LOG_LEVEL_DEBUG

#define CON_DEBUG

//#define WIFI_DEFAULT_SID "DIR-842-dde7"
//#define WIFI_DEFAULT_HOST_NAME "lampV2_2"
//#define WIFI_DEFAULT_PASSWORD "16950719"
#define WIFI_DEFAULT_SID "HOME"
#define WIFI_DEFAULT_HOST_NAME "ESP32-C3-TEST-2"
#define WIFI_DEFAULT_PASSWORD "15121820"

#define DEFAULT_MQTT_SERVER "192.168.4.254"
#define DEFAULT_TOPIC_THE_DEVICE_IS_ALIVE "deviceReady"
#define DEFAULT_TOPIC_THE_PUMP_STATE "state"
#define DEFAULT_TOPIC_PRESSURE_VALUE "pressure"
#define DEFAULT_TOPIC_TO_LISTEN_COMMANDS "commands"
#define DEFAULT_TOPIC_TO_LISTEN_SERVER_WAS_BORN "homeassistant/status"
#define DEFAULT_TOPIC_IS_THE_DEVICE_ENABLED "enabled"
#define DEFAULT_MQTT_PRESSURE_UPDATE_DIFF_ATM 0.05f

/** Firmware release label exposed in web UI and /statusApi */
#define FIRMWARE_VERSION "1.0.3"

